config/routes.rb
Rails.application.routes.draw do
  root to: 'index#inicial'
  
  get 'inicial', :to => 'index#inicial'
  get 'cartaz', :to => 'index#cartaz'
  get 'sessoes', :to => 'index#sessoes'
  get 'produtos', :to => 'index#produtos'
  get 'talk', :to => 'index#talk'
  get 'desenvolvedor', :to => 'index#desenvolvedor'

  resources :sessaos
  resources :filmes
  resources :bombonieres
  resources :cinemas
  resources :reclamacaos
  resources :promocaos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sessao.rb
class Sessao < ApplicationRecord
    
    belongs_to :cinema
    belongs_to :filme
    has_many :ingressos
    
end

app/controllers/sessaos_controller.rb
class SessaosController < ApplicationController
  before_action :set_sessao, only: [:show, :edit, :update, :destroy]

  # GET /sessaos
  # GET /sessaos.json
  def index
    @sessaos = Sessao.all
  end

  # GET /sessaos/1
  # GET /sessaos/1.json
  def show
  end

  # GET /sessaos/new
  def new
    @sessao = Sessao.new
  end

  # GET /sessaos/1/edit
  def edit
  end

  # POST /sessaos
  # POST /sessaos.json
  def create
    @sessao = Sessao.new(sessao_params)

    respond_to do |format|
      if @sessao.save
        format.html { redirect_to @sessao, notice: 'Sessao was successfully created.' }
        format.json { render :show, status: :created, location: @sessao }
      else
        format.html { render :new }
        format.json { render json: @sessao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessaos/1
  # PATCH/PUT /sessaos/1.json
  def update
    respond_to do |format|
      if @sessao.update(sessao_params)
        format.html { redirect_to @sessao, notice: 'Sessao was successfully updated.' }
        format.json { render :show, status: :ok, location: @sessao }
      else
        format.html { render :edit }
        format.json { render json: @sessao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessaos/1
  # DELETE /sessaos/1.json
  def destroy
    @sessao.destroy
    respond_to do |format|
      format.html { redirect_to sessaos_url, notice: 'Sessao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sessao
      @sessao = Sessao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sessao_params
      params.require(:sessao).permit(:cinema_id, :filme_id, :inicio, :idade, :sala, :tipo, :cadeiras, :valor)
    end
end

app/helpers/sessaos_helper.rb
module SessaosHelper
end

app/views/sessaos/_form.html.erb
<%= form_for(sessao) do |f| %>
  <% if sessao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sessao.errors.count, "error") %> prohibited this sessao from being saved:</h2>

      <ul>
      <% sessao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cinema_id %>
    <% cinema_array = Cinema.all.map { |cinema| [cinema.nome, cinema.id] } %>
    <%= f.select(:cinema_id, options_for_select(cinema_array, :selected => f.object.cinema_id)) %>
  </div>

  <div class="field">
    <%= f.label :filme_id %>
    <% filme_array = Filme.all.map { |filme| [filme.nome, filme.id] } %>
    <%= f.select(:filme_id, options_for_select(filme_array, :selected => f.object.filme_id)) %>
  </div>

  <div class="field">
    <%= f.label :inicio %>
    <%= f.text_field :inicio %>
  </div>

  <div class="field">
    <%= f.label :sala %>
    <%= f.number_field :sala %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.select :tipo, ['XD', '3D', '2D'] %>
  </div>

  <div class="field">
    <%= f.label :cadeiras %>
    <%= f.number_field :cadeiras %>
  </div>

  <div class="field">
    <%= f.label :valor %>
    <%= f.text_field :valor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sessaos/edit.html.erb
<h1>Editing Sessao</h1>

<%= render 'form', sessao: @sessao %>

<%= link_to 'Show', @sessao %> |
<%= link_to 'Back', sessaos_path %>

app/views/sessaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sessaos</h1>

<table>
  <thead>
    <tr>
      <th>Cinema</th>
      <th>Filme</th>
      <th>Inicio</th>
      <th>Sala</th>
      <th>Tipo</th>
      <th>Cadeiras</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sessaos.each do |sessao| %>
      <tr>
        <td><%= sessao.cinema.nome %></td>
        <td><%= sessao.filme.nome %></td>
        <td><%= sessao.inicio %></td>
        <td><%= sessao.sala %></td>
        <td><%= sessao.tipo %></td>
        <td><%= sessao.cadeiras %></td>
        <td><%= sessao.valor %></td>
        <td><%= link_to 'Show', sessao %></td>
        <td><%= link_to 'Edit', edit_sessao_path(sessao) %></td>
        <td><%= link_to 'Destroy', sessao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sessao', new_sessao_path %>

app/views/sessaos/new.html.erb
<h1>New Sessao</h1>

<%= render 'form', sessao: @sessao %>

<%= link_to 'Back', sessaos_path %>

app/views/sessaos/show.html.erb
<div class="container" id="showsessao">
  
  <h2 style="text-align: center;">Sessão</h2>
  
  <div class="row">
    
    <div class="col-3"><%= image_tag @sessao.filme.cartaz %></div>
    
    <div class="col">
      <h3><b>Filme: <%= @sessao.filme.nome %></b></h3>
      <br>
      <b>Cinema:</b> <%= @sessao.cinema.nome %>
      <br><br>
      <b>Início:</b> <%= @sessao.inicio %>
      <br><br>
      <b>Duração do filme: </b> <%= @sessao.filme.duracao %>
      <br><br>
      <b>Tipo:</b> <%= @sessao.tipo %>
      <br><br>
      <b>Sala:</b> <%= @sessao.sala %>
      <br><br>
      <%= link_to @sessao.filme do %>
        <div class="acesse">Ir à página do filme</div>
      <% end %>
      <%= link_to :back do %>
        <div class="acesse">Voltar às sessões</div>
      <% end %>
      
    </div>
    
  </div>
  
</div>