config/routes.rb
Rails.application.routes.draw do
  root to: 'index#inicial'
  
  get 'inicial', :to => 'index#inicial'
  get 'cartaz', :to => 'index#cartaz'
  get 'sessoes', :to => 'index#sessoes'
  get 'produtos', :to => 'index#produtos'
  get 'talk', :to => 'index#talk'
  get 'desenvolvedor', :to => 'index#desenvolvedor'

  resources :sessaos
  resources :filmes
  resources :bombonieres
  resources :cinemas
  resources :reclamacaos
  resources :promocaos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cinema.rb
class Cinema < ApplicationRecord
    
    has_many :sessaos
    has_many :reclamacaos
    
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  before_action :set_cinema, only: [:show, :edit, :update, :destroy]

  # GET /cinemas
  # GET /cinemas.json
  def index
    @cinemas = Cinema.all
  end

  # GET /cinemas/1
  # GET /cinemas/1.json
  def show
  end

  # GET /cinemas/new
  def new
    @cinema = Cinema.new
  end

  # GET /cinemas/1/edit
  def edit
  end

  # POST /cinemas
  # POST /cinemas.json
  def create
    @cinema = Cinema.new(cinema_params)

    respond_to do |format|
      if @cinema.save
        format.html { redirect_to @cinema, notice: 'Cinema was successfully created.' }
        format.json { render :show, status: :created, location: @cinema }
      else
        format.html { render :new }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cinemas/1
  # PATCH/PUT /cinemas/1.json
  def update
    respond_to do |format|
      if @cinema.update(cinema_params)
        format.html { redirect_to @cinema, notice: 'Cinema was successfully updated.' }
        format.json { render :show, status: :ok, location: @cinema }
      else
        format.html { render :edit }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cinemas/1
  # DELETE /cinemas/1.json
  def destroy
    @cinema.destroy
    respond_to do |format|
      format.html { redirect_to cinemas_url, notice: 'Cinema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cinema
      @cinema = Cinema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cinema_params
      params.require(:cinema).permit(:nome, :endereco)
    end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/_form.html.erb
<%= form_for(cinema) do |f| %>
  <% if cinema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cinema.errors.count, "error") %> prohibited this cinema from being saved:</h2>

      <ul>
      <% cinema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :endereco %>
    <%= f.text_field :endereco %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cinemas/edit.html.erb
<h1>Editing Cinema</h1>

<%= render 'form', cinema: @cinema %>

<%= link_to 'Show', @cinema %> |
<%= link_to 'Back', cinemas_path %>

app/views/cinemas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cinemas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cinemas.each do |cinema| %>
      <tr>
        <td><%= cinema.nome %></td>
        <td><%= cinema.endereco %></td>
        <td><%= link_to 'Show', cinema %></td>
        <td><%= link_to 'Edit', edit_cinema_path(cinema) %></td>
        <td><%= link_to 'Destroy', cinema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cinema', new_cinema_path %>

app/views/cinemas/new.html.erb
<h1>New Cinema</h1>

<%= render 'form', cinema: @cinema %>

<%= link_to 'Back', cinemas_path %>

app/views/cinemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cinema.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @cinema.endereco %>
</p>

<%= link_to 'Edit', edit_cinema_path(@cinema) %> |
<%= link_to 'Back', cinemas_path %>